version: "3.8" # Version specified for backwards compatibility with v1 of compose
services:
  qc-foundations-lab:
    image: artifactory.cablelabs.com/cl-secpriv-docker/public/qcfoundations:latest
    #    build: .
    container_name: qcfoundations
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: qcfoundations
        target: /usr/src/QuantumFoundations

volumes:
  qcfoundations:
