# Uncomment the following line if you have trouble running with docker-comopse (v1)
# version: "3.8"
services:
  qc-foundations-lab:
    image: artifactory.cablelabs.com/cl-secpriv-docker/public/qcfoundations:latest
    #    build: .
    container_name: qcfoundations
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: qcfoundations
        target: /usr/src/QuantumFoundations

volumes:
  qcfoundations:
